# 동적 프로그래밍(Dynamic programming)

## 행렬 경로 문제



In [10]:
import random
import numpy as np

class MatrixPathProblem:
    def __init__(self, matrix_size: int):
        size = matrix_size

        max_value = 20 + 1
        min_value = 3
        # 행렬 랜덤 초기화
        self.matrix = [[random.randrange(min_value, max_value) for i in range(size)] for j in range(size)]
        # 비용 행렬 초기화
        self.c = [[0 for i in range(size)] for j in range(size)]

        # n, n 까지 이르는 경로중 최대 점수
        self.CalculatePath(size - 1, size - 1)

        # 결과 출력
        self.print_result()

    def CalculatePath(self, i, j):
        # 초기값 설정
        self.c[0][0] = self.matrix[0][0]

        # 첫 번째 행 초기화
        for col in range(1, j + 1):
            self.c[0][col] = self.c[0][col - 1] + self.matrix[0][col]

        # 첫 번째 열 초기화
        for row in range(1, i + 1):
            self.c[row][0] = self.c[row - 1][0] + self.matrix[row][0]

        # 나머지 셀 계산
        for row in range(1, i + 1):
            for col in range(1, j + 1):
                self.c[row][col] = self.matrix[row][col] + max(self.c[row - 1][col], self.c[row][col - 1])

    def print_result(self):
        print("given matrix: ")
        print(np.matrix(self.matrix))
        print("cost matrix: ")
        print(np.matrix(self.c))

# 테스트 실행
mpp = MatrixPathProblem(10)


given matrix: 
[[15 18 13  8  8  3 19 13  5 14]
 [15 18  3 15 15 12  7 11 13 14]
 [ 6  6  8 14 20 17 15  6  8 18]
 [17  5 16 18 16 11  7 15 12 17]
 [16 20 20 20  4 10 15  3  8  7]
 [10  7  4  3  6 17 16 19 15 17]
 [18  9 20 19  5  3 20 11  3  3]
 [20  7 17 11  8  9  9 17 11 19]
 [19  7 20 15  8  6  6 18  6  8]
 [14 13 12 20  8 16  6  4 11  9]]
cost matrix: 
[[ 15  33  46  54  62  65  84  97 102 116]
 [ 30  51  54  69  84  96 103 114 127 141]
 [ 36  57  65  83 104 121 136 142 150 168]
 [ 53  62  81 101 120 132 143 158 170 187]
 [ 69  89 109 129 133 143 158 161 178 194]
 [ 79  96 113 132 139 160 176 195 210 227]
 [ 97 106 133 152 157 163 196 207 213 230]
 [117 124 150 163 171 180 205 224 235 254]
 [136 143 170 185 193 199 211 242 248 262]
 [150 163 182 205 213 229 235 246 259 271]]


## 돌 놓기

In [13]:
class PebbleStone:

    def __init__(self, size: int):
        self.size = size

        max_value = 20 + 1
        min_value = -20

        # 행렬 랜덤 초기화
        self.matrix = [[random.randrange(min_value, max_value) for i in range(3)] for j in range(size)]
        print(np.matrix(self.matrix))

        self.pattern = [[0], [1], [2], [0, 2]]
        self.compatable_p = [[1, 2], [0, 2, 3], [0, 1], [1]]
        self.peb = [[0 for i in range(4)] for j in range(size)]

        self.pebble(size)
        self.printPebbles()

    def pebble(self, n: int):
        # 초기 조건: 첫 번째 행의 비용 계산
        for p in range(4):  # 4개의 패턴
            self.peb[0][p] = sum(self.matrix[0][j] for j in self.pattern[p])

        # 동적 계획법으로 최적 비용 계산
        for i in range(1, n):  # 두 번째 행부터 마지막 행까지
            for p in range(4):  # 현재 행의 패턴
                # 이전 행에서 가능한 패턴 중 최댓값을 선택
                max_prev = max(self.peb[i-1][q] for q in self.compatable_p[p])
                # 현재 패턴의 비용 추가
                self.peb[i][p] = max_prev + sum(self.matrix[i][j] for j in self.pattern[p])

    def printPebbles(self):
        selectIdx = [-1 for _ in range(self.size)]

        # get the index of the solution
        sol_p = self.peb[self.size-1].index(max(self.peb[self.size-1]))
        selectIdx[self.size-1] = sol_p

        for i in range(self.size-1, 1, -1):
            p = selectIdx[i]
            w = sum([self.matrix[i][j] for j in self.pattern[p]])
            peb_cost = self.peb[i][p]
            selectIdx[i-1] = self.peb[i-1].index(peb_cost - w)

        for i in range(self.size):
            for j in range(3):
                sol_pattern = self.pattern[selectIdx[i]]
                str = "\x1b[{}m{}\x1b[0m ".format(31 if j in sol_pattern else 32, self.matrix[i][j])
                print(str, end='')
            print('')


# let's test
ps = PebbleStone(5)


[[-13   5  -3]
 [ -2   3  -9]
 [ 18  -4  -8]
 [  6 -20  10]
 [ -7   3 -11]]
-13 5 -3 
-2 3 -9 
18 -4 -8 
6 -20 10 
-7 3 -11 


## 행렬의 곱셈

In [14]:
class MathMultiply:
    def __init__(self, size: int):
        self.size = size

        max_value = 20 + 1
        min_value = 3

        self.p = [random.randrange(min_value, max_value) for _ in range(0, size + 1)]
        self.m = [[0 for i in range(size)] for j in range(size)]

        print(self.p)

        self.matrixchain(size)

        print(np.matrix(self.m))

        self.drawParentheses()

    def matrixchain(self, n: int):
        # 초기화: 대각선의 값은 0
        for i in range(n):
            self.m[i][i] = 0

        # l은 부분 문제의 길이
        for l in range(2, n + 1):  # l = 2부터 n까지
            for i in range(n - l + 1):  # 시작 인덱스
                j = i + l - 1  # 끝 인덱스
                self.m[i][j] = float('inf')  # 초기화
                for k in range(i, j):  # i에서 j-1까지
                    # 점화식
                    cost = self.m[i][k] + self.m[k + 1][j] + self.p[i] * self.p[k + 1] * self.p[j + 1]
                    if cost < self.m[i][j]:
                        self.m[i][j] = cost

    def drawParentheses(self):
        s_paren = []
        e_paren = []

        def rParentheses(i: int, j: int):
            if i == j:
                return False

            idx = [self.m[i][k] + self.m[k + 1][j] for k in range(i, j)]
            m_idx = min(idx)

            k = idx.index(m_idx) + i

            if rParentheses(i, k):
                s_paren.append(i)
                e_paren.append(k)

            if rParentheses(k + 1, j):
                s_paren.append(k + 1)
                e_paren.append(j)

            return True

        rParentheses(0, self.size - 1)

        result = ""
        for i in range(self.size):
            c = len([k for k in s_paren if k == i])
            for _ in range(c):
                result += "("
            result += str(i)

            c = len([k for k in e_paren if k == i])
            for _ in range(c):
                result += ")"

        print(result)


mm = MathMultiply(5)


[6, 12, 12, 16, 20, 16]
[[   0  864 2016 3936 5856]
 [   0    0 2304 6144 9984]
 [   0    0    0 3840 7680]
 [   0    0    0    0 5120]
 [   0    0    0    0    0]]
(((01)2)3)4
