# 동적 프로그래밍(Dynamic programming)

## 행렬 경로 문제



In [5]:
import random
import numpy as np

class MatrixPathProblem:
    def __init__(self, matrix_size:int):
        size=matrix_size

        max_value = 20 + 1
        min_value = 3
        # 행렬 랜덤 초기화
        self.matrix = [[random.randrange(min_value, max_value) for i in range(size)] for j in range(size)];
        # 비용 행렬 초기화
        self.c = [[0 for i in range(size)] for j in range(size)];

        # n, n 까지 이르는 경로중 최대 점수
        self.CalculatePath(size -1, size -1)

        # 결과 출력
        self.print_result()

    def CalculatePath(self, i, j):
        # 초기값 설정
        self.c[0][0] = self.matrix[0][0]

        # 첫 번째 행 초기화
        for col in range(1, j + 1):
            self.c[0][col] = self.c[0][col - 1] + self.matrix[0][col]

        # 첫 번째 열 초기화
        for row in range(1, i + 1):
            self.c[row][0] = self.c[row - 1][0] + self.matrix[row][0]

        # 나머지 셀 계산
        for row in range(1, i + 1):
            for col in range(1, j + 1):
                self.c[row][col] = self.matrix[row][col] + max(self.c[row - 1][col], self.c[row][col - 1])

    def print_result(self):
        print("given matrix: ")
        print(np.matrix(self.matrix))
        print("cost matrix: ")
        print(np.matrix(self.c))

mpp = MatrixPathProblem(10)

given matrix: 
[[ 8  3 16  4  4 11 12 14 12  4]
 [17  3  3 17  7  7 14 12 14 15]
 [20 13 20  6  9  4  6  3 15 14]
 [19  3 20 20 18 15 14 18  5  4]
 [16  9  7  9 10 11 13 16 10  9]
 [16  3 17  4  3 15 10  3  5  3]
 [20 18  9  5  4 13 17 11 11 11]
 [10  9 11 13 11 10  8 17  4 17]
 [17  6  5  5 13  3  3  5 19  3]
 [12 12 13 12 18 14 20  9  7 16]]
cost matrix: 
[[  8  11  27  31  35  46  58  72  84  88]
 [ 25  28  31  48  55  62  76  88 102 117]
 [ 45  58  78  84  93  97 103 106 121 135]
 [ 64  67  98 118 136 151 165 183 188 192]
 [ 80  89 105 127 146 162 178 199 209 218]
 [ 96  99 122 131 149 177 188 202 214 221]
 [116 134 143 148 153 190 207 218 229 240]
 [126 143 154 167 178 200 215 235 239 257]
 [143 149 159 172 191 203 218 240 259 262]
 [155 167 180 192 210 224 244 253 266 282]]


## 돌 놓기

In [7]:
class PebbleStone:

    def __init__(self, size:int):
        self.size = size

        max_value = 20 + 1
        min_value = -20

        # 행렬 랜덤 초기화
        self.matrix = [[random.randrange(min_value, max_value) for i in range(3)] for j in range(size)];
        print(np.matrix(self.matrix))

        self.pattern = [[0], [1], [2], [0, 2]]

        self.compatable_p = [[1, 2], [0, 2, 3], [0, 1], [1]]

        self.peb = [[0 for i in range(4)] for j in range(size)]

        self.pebble(size)
        self.printPebbles()


    def pebble(self, n: int):
        # 초기 조건: 첫 번째 행의 비용 계산
        for p in range(4):  # 4개의 패턴
            self.peb[0][p] = sum(self.matrix[0][j] for j in self.pattern[p])

        # 동적 계획법으로 최적 비용 계산
        for i in range(1, n):  # 두 번째 행부터 마지막 행까지
            for p in range(4):  # 현재 행의 패턴
                # 이전 행에서 가능한 패턴 중 최댓값을 선택
                max_prev = max(self.peb[i-1][q] for q in self.compatable_p[p])
                # 현재 패턴의 비용 추가
                self.peb[i][p] = max_prev + sum(self.matrix[i][j] for j in self.pattern[p])


    def printPebbles(self):
        selectIdx = [-1 for _ in range(self.size)]

        # get the index of the solution
        sol_p = self.peb[self.size-1].index( max(self.peb[self.size-1]) )
        selectIdx[self.size-1] = sol_p


        for i in range(self.size-1, 1, -1):
            p = selectIdx[i]
            w = sum([ self.matrix[i][j] for j in self.pattern[p]])
            peb_cost = self.peb[i][p]
            selectIdx[i-1] = self.peb[i-1].index( peb_cost - w )


        for i in range(self.size):
            for j in range(3):
                sol_pattern = self.pattern[selectIdx[i]]
                str = "\x1b[{}m{}\x1b[0m ".format(31 if j in sol_pattern else 32, self.matrix[i][j])
                print(str, end='')
            print('')


# let's test
ps = PebbleStone(5)

[[ -2   0   8]
 [ -2  11  -2]
 [-14 -11 -15]
 [ -5 -18   0]
 [-20 -18  12]]
-2 0 8 
-2 11 -2 
-14 -11 -15 
-5 -18 0 
-20 -18 12 


## 행렬의 곱셈

In [9]:
class MathMultiply:
    def __init__(self, size:int):
        self.size = size

        max_value = 20 + 1
        min_value = 3

        self.p = [random.randrange(min_value, max_value) for _ in range(0, size+1)]
        self.m = [[0 for i in range(size)] for j in range(size)]

        print(self.p)

        self.matrixchain(size)

        print(np.matrix(self.m))

        self.drawParentheses()


    def matrixchain(self, n: int):
        # 초기화: 대각선의 값은 0
        for i in range(n):
            self.m[i][i] = 0

        # l은 부분 문제의 길이
        for l in range(2, n + 1):  # l = 2부터 n까지
            for i in range(n - l + 1):  # 시작 인덱스
                j = i + l - 1  # 끝 인덱스
                self.m[i][j] = float('inf')  # 초기화
                for k in range(i, j):  # i에서 j-1까지
                    # 점화식
                    cost = self.m[i][k] + self.m[k + 1][j] + self.p[i] * self.p[k + 1] * self.p[j + 1]
                    if cost < self.m[i][j]:
                        self.m[i][j] = cost

    def drawParentheses(self):
        s_paren = []
        e_paren = []

        def rParentheses(i:int, j:int):
            if( i == j ):
                return False

            idx = [self.m[i][k] + self.m[k+1][j] for k in range(i, j)]
            m_idx = min(idx)

            k = idx.index(m_idx) + i

            if rParentheses(i, k):
                s_paren.append(i)
                e_paren.append(k)

            if rParentheses(k+1, j):
                s_paren.append(k+1)
                e_paren.append(j)

            return True

        rParentheses(0, self.size-1)

        result = ""
        for i in range(self.size):
            c = len([k for k in s_paren if k == i])
            for _ in range(c):
                result += "("
            result += str(i)

            c = len([k for k in e_paren if k == i])
            for _ in range(c):
                result += ")"

        print(result)



mm = MathMultiply(5)

[11, 3, 4, 9, 8, 7]
[[  0 132 405 588 723]
 [  0   0 108 324 492]
 [  0   0   0 288 512]
 [  0   0   0   0 504]
 [  0   0   0   0   0]]
0(((12)3)4)


## LCS(최장 부분 공통 순서)

In [10]:
import numpy as np

class LCS:
    def __init__(self, X, Y):
        self.X = X
        self.Y = Y

        self.m = len(X)
        self.n = len(Y)

        self.C = [[0 for i in range(self.n + 1)] for j in range(self.m + 1)]

        self.findLCS()

        print(np.matrix(self.C))

        self.printLCS()

    def findLCS(self):
        # LCS 테이블 채우기
        for i in range(1, self.m + 1):
            for j in range(1, self.n + 1):
                if self.X[i - 1] == self.Y[j - 1]:  # 문자가 같으면
                    self.C[i][j] = self.C[i - 1][j - 1] + 1
                else:  # 문자가 다르면
                    self.C[i][j] = max(self.C[i - 1][j], self.C[i][j - 1])

    def printLCS(self):
        # LCS 추적
        i, j = self.m, self.n
        lcs_result = ""

        while i > 0 and j > 0:
            if self.X[i - 1] == self.Y[j - 1]:  # 문자가 같으면
                lcs_result = self.X[i - 1] + lcs_result
                i -= 1
                j -= 1
            elif self.C[i - 1][j] >= self.C[i][j - 1]:  # 위쪽 값이 더 크면
                i -= 1
            else:  # 왼쪽 값이 더 크면
                j -= 1

        print("LCS:", lcs_result)

lcs = LCS("ACGGA", "ACTG")

[[0 0 0 0 0]
 [0 1 1 1 1]
 [0 1 2 2 2]
 [0 1 2 2 3]
 [0 1 2 2 3]
 [0 1 2 2 3]]
LCS: ACG
