# 동적 프로그래밍(Dynamic programming)

## 행렬 경로 문제



In [9]:
import random
import numpy as np

class MatrixPathProblem:
    def __init__(self, matrix_size: int):
        size = matrix_size

        max_value = 20 + 1
        min_value = 3
        # 행렬 랜덤 초기화
        self.matrix = [[random.randrange(min_value, max_value) for i in range(size)] for j in range(size)]
        # 비용 행렬 초기화
        self.c = [[0 for i in range(size)] for j in range(size)]

        # n, n 까지 이르는 경로중 최대 점수
        self.CalculatePath(size - 1, size - 1)

        # 결과 출력
        self.print_result()

    def CalculatePath(self, i, j):
        # 초기값 설정
        self.c[0][0] = self.matrix[0][0]

        # 첫 번째 행 초기화
        for col in range(1, j + 1):
            self.c[0][col] = self.c[0][col - 1] + self.matrix[0][col]

        # 첫 번째 열 초기화
        for row in range(1, i + 1):
            self.c[row][0] = self.c[row - 1][0] + self.matrix[row][0]

        # 나머지 셀 계산
        for row in range(1, i + 1):
            for col in range(1, j + 1):
                self.c[row][col] = self.matrix[row][col] + max(self.c[row - 1][col], self.c[row][col - 1])

    def print_result(self):
        print("given matrix: ")
        print(np.matrix(self.matrix))
        print("cost matrix: ")
        print(np.matrix(self.c))

# 테스트 실행
mpp = MatrixPathProblem(10)


given matrix: 
[[15 12  4 17 19 10 15 10  4 14]
 [10  7  6  9  9  4  4  8 20  5]
 [ 9 15  3  5 17 10  7 18  7 12]
 [ 9 18  5  4 19 11  6 12 12 19]
 [ 3  3  9  3  7 15 16 13 19 19]
 [19  4 10 10 11 20 17 14 18 12]
 [14 19  6 20 15  3  8 14 10 19]
 [ 4 14 14  8 11 18 11 11 19 11]
 [ 3 14 16 14 18 10 17 20  6 13]
 [19  8  6 13 18 15 14 18 10  5]]
cost matrix: 
[[ 15  27  31  48  67  77  92 102 106 120]
 [ 25  34  40  57  76  81  96 110 130 135]
 [ 34  49  52  62  93 103 110 128 137 149]
 [ 43  67  72  76 112 123 129 141 153 172]
 [ 46  70  81  84 119 138 154 167 186 205]
 [ 65  74  91 101 130 158 175 189 207 219]
 [ 79  98 104 124 145 161 183 203 217 238]
 [ 83 112 126 134 156 179 194 214 236 249]
 [ 86 126 142 156 174 189 211 234 242 262]
 [105 134 148 169 192 207 225 252 262 267]]


## 돌 놓기

In [ ]:
class PebbleStone:

    def __init__(self, size:int):
        self.size = size

        max_value = 20 + 1
        min_value = -20

        # 행렬 랜덤 초기화
        self.matrix = [[random.randrange(min_value, max_value) for i in range(3)] for j in range(size)];
        print(np.matrix(self.matrix))

        self.pattern = [[0], [1], [2], [0, 2]]

        self.compatable_p = [[1, 2], [0, 2, 3], [0, 1], [1]]

        self.peb = [[0 for i in range(4)] for j in range(size)]

        self.pebble(size)
        self.printPebbles()


    def pebble(self, n:int):
        pass


    def printPebbles(self):
        selectIdx = [-1 for _ in range(self.size)]

        # get the index of the solution
        sol_p = self.peb[self.size-1].index( max(self.peb[self.size-1]) )
        selectIdx[self.size-1] = sol_p


        for i in range(self.size-1, 1, -1):
            p = selectIdx[i]
            w = sum([ self.matrix[i][j] for j in self.pattern[p]])
            peb_cost = self.peb[i][p]
            selectIdx[i-1] = self.peb[i-1].index( peb_cost - w )


        for i in range(self.size):
            for j in range(3):
                sol_pattern = self.pattern[selectIdx[i]]
                str = "\x1b[{}m{}\x1b[0m ".format(31 if j in sol_pattern else 32, self.matrix[i][j])
                print(str, end='')
            print('')


# let's test
ps = PebbleStone(5)

[[13  6  3]
 [13 16 19]
 [ 5  3 12]
 [17  6 15]
 [15 11  5]]
[[13  6  3 16]
 [19 32 32 38]
 [37 41 44 49]
 [61 55 56 73]
 [71 84 66 75]]
13 6 3 
13 16 19 
5 3 12 
17 6 15 
15 11 5 


## 행렬의 곱셈

In [ ]:
class MathMultiply:
    def __init__(self, size:int):
        self.size = size

        max_value = 20 + 1
        min_value = 3

        self.p = [random.randrange(min_value, max_value) for _ in range(0, size+1)]
        self.m = [[0 for i in range(size)] for j in range(size)]

        print(self.p)

        self.matrixchain(size)

        print(np.matrix(self.m))

        self.drawParentheses()


    def matrixchain(self, n:int):
        pass

    def drawParentheses(self):
        s_paren = []
        e_paren = []

        def rParentheses(i:int, j:int):
            if( i == j ):
                return False

            idx = [self.m[i][k] + self.m[k+1][j] for k in range(i, j)]
            m_idx = min(idx)

            k = idx.index(m_idx) + i

            # v = m_idx + self.p[i]*self.p[k+1]*self.p[j+1]

            if rParentheses(i, k):
                s_paren.append(i)
                e_paren.append(k)

            if rParentheses(k+1, j):
                s_paren.append(k+1)
                e_paren.append(j)

            return True

        rParentheses(0, self.size-1)

        result = ""
        for i in range(self.size):
            c = len([k for k in s_paren if k == i])
            for _ in range(c):
                result += "("
            result += str(i)

            c = len([k for k in e_paren if k == i])
            for _ in range(c):
                result += ")"

        print(result)



mm = MathMultiply(5)

[15, 7, 5, 10, 14, 5]
[[   0  525 1275 2275 1650]
 [   0    0  350 1190 1125]
 [   0    0    0  700  950]
 [   0    0    0    0  700]
 [   0    0    0    0    0]]
0(1(2(34)))
